# Form implementation generated from reading ui file 'personCenter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_personCenter(object):
    def setupUi(self, personCenter):
        personCenter.setObjectName("personCenter")
        personCenter.resize(901, 598)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(personCenter)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=personCenter)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.avatarwidget = AvatarWidget(parent=self.frame_2)
        self.avatarwidget.setObjectName("avatarwidget")
        self.verticalLayout_3.addWidget(self.avatarwidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.avatarlabel = StrongBodyLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatarlabel.sizePolicy().hasHeightForWidth())
        self.avatarlabel.setSizePolicy(sizePolicy)
        self.avatarlabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.avatarlabel.setText("")
        self.avatarlabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.avatarlabel.setObjectName("avatarlabel")
        self.verticalLayout_3.addWidget(self.avatarlabel)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.changepwdtoolButton = PrimaryPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changepwdtoolButton.sizePolicy().hasHeightForWidth())
        self.changepwdtoolButton.setSizePolicy(sizePolicy)
        self.changepwdtoolButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changepwdtoolButton.setText("")
        self.changepwdtoolButton.setObjectName("changepwdtoolButton")
        self.verticalLayout_4.addWidget(self.changepwdtoolButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(personCenter)
        QtCore.QMetaObject.connectSlotsByName(personCenter)

    def retranslateUi(self, personCenter):
        _translate = QtCore.QCoreApplication.translate
        personCenter.setWindowTitle(_translate("personCenter", "Form"))
from qfluentwidgets import AvatarWidget, PrimaryPushButton, StrongBodyLabel
